CREATE TABLE IF NOT EXISTS coffeeshops(
    id BIGINT(19) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(255) DEFAULT NULL,
    price_of_coffee DOUBLE NOT NULL,
    power_accessible BOOLEAN NOT NULL,
    internet_reliability SMALLINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
)  ENGINE=INNODB;
