spring:
  datasource:
    url: &dbURL jdbc:mysql://localhost:3306/kotlin_crud_db
    username: &dbUser root
    password: &dbPassword 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

okta:
  oauth2:
    issuer: https://dev-63669975.okta.com/oauth2/default
    clientId: 0oa2gfjz71LnTQhAg5d7
